apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: vae-outlier
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
      - image: seldonio/cifar10od:0.0.4
        imagePullPolicy: Always
        args:
        - --model_name
        - vaeod
        - --storage_uri
        - ./vae_outlier_detector/
        - --reply_url
        - http://seldon-request-logger.default
        - --event_type
        - org.kubeflow.serving.inference.outlier
