apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: seldon-request-logger-trigger
  namespace: default
spec:
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: seldon-request-logger
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: seldon-request-logger
  namespace: default
  metadata:
    labels:
    fluentd: "true"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: docker.io/seldonio/seldon-request-logger-cifar:0.2.0
          imagePullPolicy: Always
          env:
           - name: ELASTICSEARCH_HOST
             value: "elasticsearch-master.logs.svc.cluster.local"
           - name: ELASTICSEARCH_PORT
             value: "9200"
