apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: seldon-request-logger
  namespace: default
  metadata:
    labels:
    fluentd: "true"
spec:
  template:
    spec:
      containers:
        - image: docker.io/ryandawsonuk/seldon-request-logger-cifar:0.0.1
          imagePullPolicy: Always
          env:
           - name: ELASTICSEARCH_HOST
             value: "elasticsearch-master.logs.svc.cluster.local"
           - name: ELASTICSEARCH_PORT
             value: "9200"
