apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "mnist"
spec:
  default:
    predictor:
      minReplicas: 1
      custom:
        container:
          image: seldonio/mnist:0.0.3
          args:
            - --model_name
            - mnist
            - --model_dir
            - ./model_mnist/
            - --http_port
            - "8081"
      logger:
        mode: request
