---
name: 'mmd random encoder v1'                    # Name/id of detector spec file

# The drift detector (required)
detector:
  name: 'MMDDrift'                 # one of alibi_detect.cd.__all__
  p_val: .05                       # optionally specify detector kwargs
  n_permutations: 100

# Preprocessing step for drift detector (optional) 
preprocess:
  type: 'model'                 # 'model', 'transformerembedding' or ... TODO - custom helper options such as build_conv
  model: 
    source: '@random_encoder.tf'
    type: 'encoder'              # 'hidden', 'encoder' # TODO - what else?
  batch_size: 512     

other:
  log_path: 'logs'              # directory to log to (optional) TODO - might be nice to output to log file if we are also using config files...
