---
name: 'mmd cifar10 resnet'                    # Name/id of detector spec file

# The drift detector (required)
detector:
  name: 'MMDDrift'                 # one of alibi_detect.cd.__all__
  p_val: .05                       # optionally specify detector kwargs
  configure_kernel_from_x_ref: False
  n_permutations: 1000

# Preprocessing step for drift detector (optional) 
preprocess:
  type: 'model'                 # 'model', 'transformerembedding' or ... TODO - custom helper options such as build_conv
  model: 
    source: './models/resnet32.h5'
    type: 'hidden'              # 'hidden', 'encoder' # TODO - what else?
    layer: -1                   # Layer index to extract layer from. Only relevent for type='hidden'.
    flatten: False              # True or false. Only relevent for type='hidden'.
    batch_size: 128

other:
  log_path: 'logs'              # directory to log to (optional) TODO - might be nice to output to log file if we are also using config files...
