# This github action builds Alibi Detect and publishes it to PyPI.
# It is only run when a new tag is pushed to github.
# See https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
name: Publish 📦 to PyPI 

# Only run when tags starting with "v" are pushed
on: 
  push:
    tags:
      - 'v*'
  release:
    types: [published]

jobs:
  build-and-publish:
    name: Build and publish
    runs-on: ubuntu-18.04

    steps:
    # Setup Python
    - uses: actions/checkout@master
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    # Build
    - name: Build a binary wheel and a source tarball
      run: make build

    # Publish to Test PyPI if this action was triggered by pushing a v* tag
    - name: Publish 📦 to Test PyPI
      if: github.event_name == 'push'  # check for `push` since action only triggered for tag pushes
      run: |
        python -m pip install .
        echo "Dummy release of alibi-detect..."
        python -c "from alibi_detect.version import __version__; print(__version__)" 
      #     uses: pypa/gh-action-pypi-publish@release/v1
      #     with:
      #       password: ${{ secrets.TEST_PYPI_API_TOKEN }}
      #       repository_url: https://test.pypi.org/legacy/

    # If this action was triggered by a GitHub release, publish the associated tag to PyPI
    - name: Publish 📦 to PyPI
      if: github.event_name == 'release'
      run: |
        python -m pip install .
        echo "Dummy release of alibi-detect..."
        python -c "from alibi_detect.version import __version__; print(__version__)" 
        #      uses: pypa/gh-action-pypi-publish@release/v1
        #      with:
        #        password: ${{ secrets.PYPI_API_TOKEN }}        
